import java.sql.*;


public class MySQLTest {

    public static void main(String[] args) throws Exception {



        /**
         * Create test member objects to populate datatbase
         *
         *
         **/


        Member member;
        member = new Member();

        member.setFirstName("james");
        member.setLastName("elder");
        member.setDob("23/12/1954");
        member.setEmail("ndawg@hotmail.com");
        member.setWlsNumber("1236");
        member.setContactNumber("07577977799");
        member.setUsername("Jones100");
        member.setPassword("");


        //Test insertion of member details into accounts table (username,password)
        String SQL = "INSERT INTO Accounts(Username,Password) VALUES (?,?)";

        //Make Connection and ready a  prepared statmenent to execute
       Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test");
        PreparedStatement userStatement = connection.prepareStatement(SQL, Statement.RETURN_GENERATED_KEYS);

        userStatement.setString(1,member.getUsername());
        userStatement.setString(2,member.getPassword());
        userStatement.executeUpdate();

        ResultSet userKeys = userStatement.getGeneratedKeys();
        userKeys.next();
        member.setMemberID(userKeys.getInt(1));
        userStatement.close();


        //Print out Member ID generated
        System.out.println("Member ID generated by database engine : "+member.getMemberID());


        //Test insertion of an address(Street address, city, postcode)
        Address address = new Address();

        address.setStreetAddress("1 Woodlands");
        address.setCity("Glesga");
        address.setPostcode("g49eu");

        //Insert address data into addresses table
        String AddressSQL = " INSERT INTO Addresses(Street_address,City,Postcode) VALUES (?,?,?)";
        PreparedStatement addressStatement = connection.prepareStatement(AddressSQL,Statement.RETURN_GENERATED_KEYS);

        addressStatement.setString(1,address.getStreetAddress());
        addressStatement.setString(2,address.getCity());
        addressStatement.setString(3,address.getPostcode());
        addressStatement.executeUpdate();
        ResultSet addressKeys = addressStatement.getGeneratedKeys();
        addressKeys.next();

        //Get and set addressID generated by database for members Address ID
        member.setAddressID(addressKeys.getInt(1));
        addressStatement.close();

        //Print out Address ID generated
        System.out.println("Address generated by database engine : "+member.getAddressID());


        //Finally test insertion of a member object using generated keys from the queries above
        PreparedStatement statement = connection.prepareStatement("INSERT INTO Members(Member_ID,First_name,Last_name,Date_of_birth,Email," +
                                                                       "Contact_number,Address_ID,WLS_number) VALUES (?,?,?,?,?,?,?,?)");

        statement.setInt   (1,member.getMemberID());
        statement.setString(2,member.getFirstName());
        statement.setString(3,member.getLastName());
        statement.setString(4,String.valueOf(member.getDob()));
        statement.setString(5,member.getEmail());
        statement.setString(6,member.getContactNumber());
        statement.setInt   (7,member.getAddressID());
        statement.setString(8,member.getWlsNumber());

        statement.executeUpdate();
        statement.close();


        connection.close();
        System.out.println("User has been registered");



    }




}
